# Generated by Django 6.0.2 on 2026-02-24 17:00

import easy_thumbnails.fields
import phonenumber_field.modelfields
import sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان پیام')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='پاسخ داده شده')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('address', models.TextField(verbose_name='ادرس')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='لوگو')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('support_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن پشتیبان')),
                ('site_tax', models.PositiveSmallIntegerField(verbose_name='مالیات زیر ساخت')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=sitesetting.models.photo_path_upload_to, verbose_name='عکس')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن ')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
        ),
    ]
