# Generated by Django 6.0.2 on 2026-02-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'تیم'},
        ),
    ]
