# Generated by Django 6.0.2 on 2026-02-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_alter_contact_options_alter_site_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='پاسخ داده شده'),
        ),
    ]
