# Generated by Django 6.0.2 on 2026-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='minutes_to_allow_cancelling_the_order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='دقیقه برای اجازه کنسل کردن سفارش'),
        ),
    ]
