# Generated by Django 6.0.2 on 2026-02-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_site_minutes_to_allow_cancelling_the_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='minutes_to_allow_cancelling_the_order_after_payment',
            field=models.PositiveSmallIntegerField(default=120, verbose_name=' دقیقه برای اجازه کنسل کردن سفارش بعد از پرداخت'),
        ),
    ]
