# Generated by Django 6.0.2 on 2026-02-27 14:08

import django.utils.timezone
import phonenumber_field.modelfields
import user.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('M', 'مذکر'), ('F', 'مونث')], max_length=255, verbose_name='جنسیت')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='شماره')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد otp')),
                ('otp_expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای ')),
                ('type_of_user', models.CharField(choices=[('R', 'عادی'), ('S', 'سالون دار'), ('A', 'ادمین')], default='R', max_length=255, verbose_name='نوع کاربر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تایید اطلاعات')),
                ('login_request', models.BooleanField(default=False, verbose_name='درخواست لاگین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت نام')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', user.managers.UserManager()),
            ],
        ),
    ]
