# Generated by Django 6.0.2 on 2026-02-14 16:28

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_request',
            field=models.BooleanField(default=False, verbose_name='درخواست لاگین'),
        ),
        migrations.AlterField(
            model_name='user',
            name='PhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'مذکر'), ('F', 'مونث')], max_length=255, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='تایید اطلاعات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد otp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای '),
        ),
    ]
