# Generated by Django 6.0.2 on 2026-02-27 14:08

import easy_thumbnails.fields
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('link', models.CharField(max_length=1000, verbose_name='لینک')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=orders.models.photo_path_upload_to, verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تایخ پرداخت')),
                ('status', models.CharField(choices=[('awaitingـpayment', 'منتظر پرداخت'), ('cancelled', 'کنسل شده'), ('awaiting_paid_to_admin', 'منتظر پرداخت به ادمین'), ('paid', 'پرداخت شده')], default='awaitingـpayment', max_length=255, verbose_name='وضعیت')),
                ('price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت تاریخ چه')),
                ('payment_code', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='کد پیگیری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت')),
                ('status', models.CharField(choices=[('awaiting', 'در حالت انتظار'), ('return_request', 'درخواست برداشت'), ('paid', 'پرداخت شده')], default='awaiting', max_length=255, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول',
            },
        ),
    ]
