# Generated by Django 6.0.2 on 2026-02-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_userwallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
