# Generated by Django 6.0.2 on 2026-02-26 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_salon_alter_order_user'),
        ('ticket', '0012_salon_accept_ticket_cancelling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ticket.salonticket', verbose_name='بلیت'),
        ),
    ]
