# Generated by Django 6.0.2 on 2026-02-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free', models.BooleanField(default=True, verbose_name='وضعیت خالی بودن :')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بلیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('date_of_departure', models.DateTimeField(verbose_name='تاریخ حرکت')),
                ('count_ofـpassengers', models.PositiveSmallIntegerField(verbose_name='تعداد مسافران')),
            ],
        ),
    ]
