# Generated by Django 6.0.2 on 2026-02-24 17:00

import django.contrib.gis.db.models.fields
import easy_thumbnails.fields
import phonenumber_field.modelfields
import ticket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام سالون')),
                ('address', models.TextField(verbose_name='ادرس')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to=ticket.models.photo_path_upload_to, verbose_name='لوگو')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('support_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='شماره تلفن پشتیبان')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('working_hours_start', models.TimeField(verbose_name='شروع ساعت کاری ')),
                ('working_hours_end', models.TimeField(verbose_name='پایان ساعت کاری ')),
                ('accepted_gender', models.CharField(choices=[('M', 'مذکر'), ('F', 'مونث'), ('B', 'هردو')], verbose_name='جنسیت مورد قبول')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='موقعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='SalonGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=ticket.models.salon_gallery_photo_path_upload_to, verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='SalonTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('accepted_gender', models.CharField(choices=[('M', 'مذکر'), ('F', 'مونث'), ('B', 'هردو')], verbose_name='جنسیت مورد قبول')),
                ('working_datetime_start', models.DateTimeField(verbose_name='شروع ساعت کاری ')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='ظرفیت')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دسته')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(upload_to=ticket.models.category_photo_path_upload_to, verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
        ),
    ]
