# Generated by Django 6.0.2 on 2026-02-27 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salon', to=settings.AUTH_USER_MODEL, verbose_name='ادمین'),
        ),
        migrations.AddField(
            model_name='salongallery',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ticket.salon'),
        ),
        migrations.AddField(
            model_name='salonticket',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.salon', verbose_name='سالون'),
        ),
        migrations.AddField(
            model_name='salonticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticketcategory', verbose_name='دسته'),
        ),
    ]
