# Generated by Django 6.0.2 on 2026-02-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'سالون ', 'verbose_name_plural': 'سالون ها'},
        ),
        migrations.AlterModelOptions(
            name='salongallery',
            options={'verbose_name': 'عکس ', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='salonticket',
            options={'verbose_name': 'بلیت ', 'verbose_name_plural': 'بلیت'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name': 'دسته ', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
