# Generated by Django 6.0.2 on 2026-02-24 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_salon_options_alter_salongallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='موقعیت'),
        ),
    ]
