# Generated by Django 6.0.2 on 2026-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_salon_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='salongallery',
            name='sort_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد اولویت بندی (هر چه بزرگتر بالاتر نمایش داده می شود)'),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='sort_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد اولویت بندی (هر چه بزرگتر بالاتر نمایش داده می شود)'),
        ),
    ]
