# Generated by Django 6.0.2 on 2026-02-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_salongallery_sort_number_ticketcategory_sort_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='sort_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد اولویت بندی (هر چه بزرگتر بالاتر نمایش داده می شود)'),
        ),
        migrations.AddField(
            model_name='salonticket',
            name='sort_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد اولویت بندی (هر چه بزرگتر بالاتر نمایش داده می شود)'),
        ),
    ]
