# Generated by Django 6.0.2 on 2026-02-25 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_salon_sort_number_salonticket_sort_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='salongallery',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ticket.salon'),
            preserve_default=False,
        ),
    ]
