# Generated by Django 6.0.2 on 2026-02-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_salongallery_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonticket',
            name='current_capacity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ظرفیت'),
        ),
    ]
