# Generated by Django 6.0.2 on 2026-02-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_salonticket_current_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonticket',
            name='current_capacity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name=' فعلی ظرفیت'),
        ),
    ]
