# Generated by Django 6.0.2 on 2026-02-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_salon_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='accept_ticket_cancelling',
            field=models.BooleanField(default=True, verbose_name='قبول کردن کنسل کردن بعد پرداخت'),
        ),
    ]
